#!/bin/sh

make_dist_file=`pwd`
make_dist_file="$make_dist_file/make_dist.out"

if [ -z $1 ]; then
    echo $0 email_version
    exit;
fi

# Check files and make sure we have everyone ready.
if [ ! -f configure.in.dist ]
then
    echo "No configure.in available..."
    exit -1
fi

DATE="`date +%x-%I:%M:%S%p_%Z`"
VERSION="$1"

printf "\rSetting up configure scripts and version info..."
echo "s!@date@!$DATE!" > "$make_dist_file"
echo "s!@ver@!$VERSION!" >> "$make_dist_file"
sed -f "$make_dist_file" configure.in.dist > configure.in
echo "$VERSION" > VERSION
autoheader
autoconf > /dev/null 2>&1
cd dlib
autoheader
autoconf
cd ..

mkdir -p "email-${VERSION}/dlib"
cmd=`git archive master | tar -x -C email-${VERSION}`

printf "\rDoing a git...            "
$cmd > /dev/null

# Get dlib
cd dlib
git archive master | tar -x -C ../email-${VERSION}/dlib > /dev/null
cd ../email-${VERSION}

# Fix VERSION and configure.ac script in release dir
printf "\rParsing files and creating ./configure...      "
sed -f "$make_dist_file" configure.in.dist > configure.in
autoheader
autoconf > /dev/null 2>&1
rm -f configure.in.dist make_dist
cd dlib
autoheader
autoconf
cd ..

# Tar and gzip distrobution file
cd ..
if [ ! -d dist ]; then
	mkdir dist
fi
printf "\rTaring and gziping up email-$VERSION...        "
tar -cf dist/email-"$VERSION".tar email-"$VERSION"
cd dist
gzip email-${VERSION}.tar
bzip2 email-${VERSION}.tar
rm -f "$make_dist_file"

printf "\rDistribution file is at $HOME/email-$VERSION.tar.gz\n"
